### PR TITLE
Added AdaBoostRegressor

### PR DESCRIPTION
**Pull request by 26tanishabanik**
Changes made in the following file:
 https://github.com/blobcity/autoai/blob/main/blobcity/config/regressor_config.py
Issue #60

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
@26tanishabanik 

avoid \ in configuration for consistency

           "base_estimator":{'object':[tree.DecisionTreeRegressor(max_depth=3),tree.DecisionTreeRegressor(max_depth=5),\
                                                                                        tree.DecisionTreeRegressor(max_depth=7),\
                                                                                         tree.DecisionTreeRegressor(max_depth=10))]},

keep it like: 

              "base_estimator":{'object':[
                              tree.DecisionTreeRegressor(max_depth=3),
                              tree.DecisionTreeRegressor(max_depth=5),
                              tree.DecisionTreeRegressor(max_depth=7),
                              tree.DecisionTreeRegressor(max_depth=10))
                ]},

**Comment by 26tanishabanik** [comment]
> @26tanishabanik
> 
> avoid \ in configuration for consistency
> 
> ```
>        "base_estimator":{'object':[tree.DecisionTreeRegressor(max_depth=3),tree.DecisionTreeRegressor(max_depth=5),\
>                                                                                     tree.DecisionTreeRegressor(max_depth=7),\
>                                                                                      tree.DecisionTreeRegressor(max_depth=10))]},
> ```
> 
> keep it like:
> 
> ```
>           "base_estimator":{'object':[
>                           tree.DecisionTreeRegressor(max_depth=3),
>                           tree.DecisionTreeRegressor(max_depth=5),
>                           tree.DecisionTreeRegressor(max_depth=7),
>                           tree.DecisionTreeRegressor(max_depth=10))
>             ]},
> ```

Sure

**Comment by Thilakraj1998** [comment]
@26tanishabanik for integer and float parameter specify only min and max value to consider

for example : 
             "n_estimators":{'int':[10, 5000]}, 
             "learning_rate":{'float':[1e-3,0.1]},

**Comment by 26tanishabanik** [comment]
> @26tanishabanik for integer and float parameter specify only min and max value to consider
> 
> for example : "n_estimators":{'int':[10, 5000]}, "learning_rate":{'float':[1e-3,0.1]},

Okay

**Comment by 26tanishabanik** [comment]
> @26tanishabanik for integer and float parameter specify only min and max value to consider
> 
> for example : "n_estimators":{'int':[10, 5000]}, "learning_rate":{'float':[1e-3,0.1]},

Done

**Pull request merged**
