### PR TITLE
Add BernoulliNB Classifier Implementation ID #43

### PR DESCRIPTION
**Pull request by melan96**
added optimal hyper-parameters for the `classifier_config.py`. By this PR  completely solve the #43 issue

✅ Parameter (alpha, fit_prior) added

### CODE REVIEW

**Comment by melan96** [comment]
@sanketsarang please check this PR

**Comment by melan96** [comment]
@sanketsarang seems to be build failed by pip installation. can you go through this and mentioned the possible cases which need to complete this issue? 

additional note : codeql seems to be failed on `cliff` installation on codebase.

**Comment by Thilakraj1998** [comment]
@melan96 
for BernoulliNB parameters:

do follow conventions used in randomforestclassifier parameters
where each list consist of only 2 entry  at index 1 min value and index 2 max value for the certain parameter

for example

         'parameter':{'datatype':[minvalue,maxvalue]}
         'alpha'      : {'float':[0.01,1]},

**Comment by melan96** [comment]
@Thilakraj1998 Thank for quick response!. I will fix these and resubmit a PR as soon as possible !  👋

**Comment by melan96** [comment]
This PR fixed on #55. This PR will be closed

**Pull request closed without merging**
