### PR TITLE
Added LassoLars

### PR DESCRIPTION
**Pull request by naresh1205**
This aims to solve issue  #71

### CODE REVIEW

**Comment by Thilakraj1998** [comment]
@naresh1205 keep epsilon value from 

      [1e-6,0.1]

same for alpha:

      [1e-4, 0.1]

**Comment by Thilakraj1998** [comment]
@naresh1205 do consider doing a fetch operation on the fork. we have updated some key name in configuration files.

also key as LassoLars for your configuration

**Comment by naresh1205** [comment]
@Thilakraj1998 is this good to merge, or are there any changes to be done?

**Comment by Thilakraj1998** [comment]
@naresh1205  you still have older version of classifer_config and regression_configs

**Pull request merged**
